[package]
edition = "2021"
name = "scene_splash"
version = "0.1.0"

[dependencies]
bevy = "0.14.2"
fw_anim = {path = "../../fw/fw_anim"}
fw_button = {path = "../../fw/fw_button"}
fw_ftxm = {path = "../../fw/fw_ftxm"}
scene_base = {path = "../scene_base"}
